### ISSUE TITLE
希望楼主出一个node+mongodb+vue如何部署上线的教程

### ISSUE THREAD

**Issue by hi-zhaoyeqing** [bestRenekton/taoLand#2]
希望楼主出一个node+mongodb+vue如何部署上线的教程，星星已送上。

**Comment by bestRenekton** [comment]
首页最底部写的2篇都是部署的啊，自己服务器是centos7的，安了apache，node，mongoDB之后,前端的代码打包好后放上去，服务器node启动起来就可以了


另外还可以查看[docker分支](https://github.com/bestRenekton/taoLand/tree/taoland_docker)，使用docker部署超级方便
