### ISSUE TITLE
按照食用步骤启动后只有登录注册功能，其他功能不能用

### ISSUE THREAD

**Issue by samuelchen12** [bestRenekton/taoLand#3]
按照食用步骤启动后只有登录注册功能，其他功能不能用，是不是我这边哪里出问题了？小白跪求指教

**Comment by 272777203** [comment]
修改源码文件 api.js 注册接口里面的type 改为1再重新跑一次就可以打开超级管理员的界面实现其他功能

**Comment by 272777203** [comment]
> 按照食用步骤启动后只有登录注册功能，其他功能不能用，是不是我这边哪里出问题了？小白跪求指教

修改源码文件 api.js 注册接口里面的type 改为1再重新跑一次就可以打开超级管理员的界面实现其他功能

**Comment by bestRenekton** [comment]
注册后，需要到数据库手动修改自己账号的type，改成管理员权限
